from pathlib import Path

datasets = {
    "euroc": {
        "path": Path("/storage/local/ssd/mayom/Documents/apps/datasets/euroc"),
        "list": [
            "MH_01_easy",
            "MH_02_easy",
            "MH_03_medium",
            "MH_04_difficult",
            "MH_05_difficult",
            "V1_01_easy",
            "V1_02_medium",
            "V1_03_difficult",
            "V2_01_easy",
            "V2_02_medium",
            "V2_03_difficult",
            "V2_03_difficult_sanitized",
        ],
    },
    "tumvi": {
        "path": Path("/storage/local/ssd/mayom/Documents/apps/datasets/tumvi"),
        "list": [
            "dataset-room1_512_16",
            "dataset-room2_512_16",
            "dataset-room3_512_16",
            "dataset-room4_512_16",
            "dataset-room5_512_16",
            "dataset-room6_512_16",
        ],
    },
    "msd": {
        "path": Path("/storage/local/ssd/mayom/Documents/apps/datasets/msd"),
        "list": [
            Dataset(
                "MIO01",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO01_hand_puncher_1",
            ),
            Dataset(
                "MIO02",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO02_hand_puncher_2",
            ),
            Dataset(
                "MIO03",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO03_hand_shooter_easy",
            ),
            Dataset(
                "MIO04",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO04_hand_shooter_hard",
            ),
            Dataset(
                "MIO05",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO05_inspect_easy",
            ),
            Dataset(
                "MIO06",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO06_inspect_hard",
            ),
            Dataset(
                "MIO07",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO07_mapping_easy",
            ),
            Dataset(
                "MIO08",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO08_mapping_hard",
            ),
            Dataset(
                "MIO09",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO09_short_1_updown",
            ),
            Dataset(
                "MIO10",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO10_short_2_panorama",
            ),
            Dataset(
                "MIO11",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO11_short_3_backandforth",
            ),
            Dataset(
                "MIO12",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO12_moving_screens",
            ),
            Dataset(
                "MIO13",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO13_moving_person",
            ),
            Dataset(
                "MIO14",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO14_moving_props",
            ),
            Dataset(
                "MIO15",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO15_moving_person_props",
            ),
            Dataset(
                "MIO16",
                "M_monado_datasets/MI_valve_index/MIO_others/MIO16_moving_screens_person_props",
            ),
            Dataset(
                "MIPB0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPB_beat_saber/MIPB01_beatsaber_100bills_360_normal",
            ),
            Dataset(
                "MIPB0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPB_beat_saber/MIPB02_beatsaber_crabrave_360_hard",
            ),
            Dataset(
                "MIPB0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPB_beat_saber/MIPB03_beatsaber_countryrounds_360_expert",
            ),
            Dataset(
                "MIPB0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPB_beat_saber/MIPB04_beatsaber_fitbeat_hard",
            ),
            Dataset(
                "MIPB0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPB_beat_saber/MIPB05_beatsaber_fitbeat_360_expert",
            ),
            Dataset(
                "MIPB0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPB_beat_saber/MIPB06_beatsaber_fitbeat_expertplus_1",
            ),
            Dataset(
                "MIPB0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPB_beat_saber/MIPB07_beatsaber_fitbeat_expertplus_2",
            ),
            Dataset(
                "MIPB0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPB_beat_saber/MIPB08_beatsaber_long_session_1",
            ),
            Dataset(
                "MIPP0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPP_pistol_whip/MIPP01_pistolwhip_blackmagic_hard",
            ),
            Dataset(
                "MIPP0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPP_pistol_whip/MIPP02_pistolwhip_lilith_hard",
            ),
            Dataset(
                "MIPP0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPP_pistol_whip/MIPP03_pistolwhip_requiem_hard",
            ),
            Dataset(
                "MIPP0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPP_pistol_whip/MIPP04_pistolwhip_revelations_hard",
            ),
            Dataset(
                "MIPP0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPP_pistol_whip/MIPP05_pistolwhip_thefall_hard_2pistols",
            ),
            Dataset(
                "MIPP0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPP_pistol_whip/MIPP06_pistolwhip_thegrave_hard",
            ),
            Dataset(
                "MIPT0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPT_thrill_of_the_fight/MIPT01_thrillofthefight_setup",
            ),
            Dataset(
                "MIPT0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPT_thrill_of_the_fight/MIPT02_thrillofthefight_fight_1",
            ),
            Dataset(
                "MIPT0",
                "M_monado_datasets/MI_valve_index/MIP_playing/MIPT_thrill_of_the_fight/MIPT03_thrillofthefight_fight_2",
            ),
            Dataset(
                "MGO01", "M_monado_datasets/MG_reverb_g2/MGO_others/MGO01_low_light"
            ),
            Dataset(
                "MGO02", "M_monado_datasets/MG_reverb_g2/MGO_others/MGO02_hand_puncher"
            ),
            Dataset(
                "MGO03",
                "M_monado_datasets/MG_reverb_g2/MGO_others/MGO03_hand_shooter_easy",
            ),
            Dataset(
                "MGO04",
                "M_monado_datasets/MG_reverb_g2/MGO_others/MGO04_hand_shooter_hard",
            ),
            Dataset(
                "MGO05", "M_monado_datasets/MG_reverb_g2/MGO_others/MGO05_inspect_easy"
            ),
            Dataset(
                "MGO06", "M_monado_datasets/MG_reverb_g2/MGO_others/MGO06_inspect_hard"
            ),
            Dataset(
                "MGO07", "M_monado_datasets/MG_reverb_g2/MGO_others/MGO07_mapping_easy"
            ),
            Dataset(
                "MGO08", "M_monado_datasets/MG_reverb_g2/MGO_others/MGO08_mapping_hard"
            ),
            Dataset(
                "MGO09",
                "M_monado_datasets/MG_reverb_g2/MGO_others/MGO09_short_1_updown",
            ),
            Dataset(
                "MGO10",
                "M_monado_datasets/MG_reverb_g2/MGO_others/MGO10_short_2_panorama",
            ),
            Dataset(
                "MGO11",
                "M_monado_datasets/MG_reverb_g2/MGO_others/MGO11_short_3_backandforth",
            ),
            Dataset(
                "MGO12",
                "M_monado_datasets/MG_reverb_g2/MGO_others/MGO12_freemovement_long_session",
            ),
            Dataset(
                "MGO13",
                "M_monado_datasets/MG_reverb_g2/MGO_others/MGO13_sudden_movements",
            ),
            Dataset(
                "MGO14",
                "M_monado_datasets/MG_reverb_g2/MGO_others/MGO14_flickering_light",
            ),
            Dataset(
                "MGO15", "M_monado_datasets/MG_reverb_g2/MGO_others/MGO15_seated_screen"
            ),
            Dataset(
                "MOO01",
                "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO01_hand_puncher_1",
            ),
            Dataset(
                "MOO02",
                "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO02_hand_puncher_2",
            ),
            Dataset(
                "MOO03",
                "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO03_hand_shooter_easy",
            ),
            Dataset(
                "MOO04",
                "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO04_hand_shooter_hard",
            ),
            Dataset(
                "MOO05",
                "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO05_inspect_easy",
            ),
            Dataset(
                "MOO06",
                "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO06_inspect_hard",
            ),
            Dataset(
                "MOO07",
                "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO07_mapping_easy",
            ),
            Dataset(
                "MOO08",
                "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO08_mapping_hard",
            ),
            Dataset(
                "MOO09",
                "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO09_short_1_updown",
            ),
            Dataset(
                "MOO10",
                "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO10_short_2_panorama",
            ),
            Dataset(
                "MOO11",
                "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO11_short_3_backandforth",
            ),
            Dataset(
                "MOO12",
                "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO12_freemovement_long_session",
            ),
            Dataset(
                "MOO13",
                "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO13_sudden_movements",
            ),
            Dataset(
                "MOO14",
                "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO14_flickering_light",
            ),
            Dataset(
                "MOO15",
                "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO15_seated_screen",
            ),
            Dataset(
                "MOO16", "M_monado_datasets/MO_odyssey_plus/MOO_others/MOO16_still"
            ),
        ],
    },
}
